name: Qodana
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

jobs:
  qodana:
    runs-on: github/codeql-action/upload-sarif@v2

    steps:
      - uses: actions/checkout@v3
        with:
          sarif_file: ${{ runner.temp }}/qodana/results/qodana.sarif.json
          fetch-depth: 0
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2023.1.1