name: Qodana

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

jobs:
  qodana:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '19'
      - name: Install Dependencies
        run: npm install
      - name: Build Next.js App
        run: npm run build
      - name: Run Tests
        run: npm test
      - name: Validate TypeScript Types
        run: npm run type-check
      - name: Run ESLint
        run: npx eslint .
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2023.1.0
        with:
          qodana_version: 'latest'
